---
- name: Download install script
  command: curl -sL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o /tmp/ohmyzsh.sh

- name: Make script executable
  command: chmod +x /tmp/ohmyzsh.sh

- name: Install Oh My ZSH
  command: /tmp/ohmyzsh.sh --unattended
