wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb sudo apt install ./dive_0.9.2_linux_amd64.deb
---
- name: Download Dive
  command: wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb -O /tmp/dive.deb

- name: Install Dive
  apt:
    deb: /tmp/dive.deb