---
- name: Install Node PPA
  command: curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh

- name: Make nodesource_setup executable
  command: chmod +x /tmp/nodesource_setup.sh

- name: Install Node
  command: /tmp/nodesource_setup.sh

- name: Install Node16
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nodejs
